#:include kv/homepage.kv
#:include kv/ajustepage.kv

FloatLayout:
    canvas: 
        Color:
            rgb: (1, 1, 1, 1)
        Rectangle
            size: self.size
            pos: self.pos
    rows: 1
    ScreenManager:
        id: screen_manager
        HomePage:
            name: "homepage"
            id: homepage

        AjustePage:
            name: "ajustepage"
            id: ajustepage